#!/usr/bin/env python3
"""
GNR-SMU Telemetry Exporter — profile-backed (Granite Ridge, Vermeer read-only)
Usage:
  python3 export_telemetry.py              # 5 JSON snapshots -> gnr_telemetry_dump.json
  python3 export_telemetry.py --csv        # named CSV snapshot -> gnr_telemetry.csv
  python3 export_telemetry.py --live N     # CSV live logging every N seconds (Ctrl+C to stop)
  python3 export_telemetry.py --temps      # print one per-core temperature snapshot
"""
import struct
import json
import time
import csv
import sys
import argparse
import os

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from gnr_smu.hardware import get_hardware_profile  # noqa: E402
from gnr_smu.telemetry import (  # noqa: E402,F401 (re-exported for compatibility)
    COMMON_FIELDS,
    _EXTRA_9800X3D,
    _EXTRA_9950X3D,
    _EXTRA_VERMEER,
    floats_to_row,
    global_fields,
    live_power_index,
    named_fields,
)

PM_TABLE_PATH = "/sys/kernel/ryzen_smu_drv/pm_table"
VERSION_PATH  = "/sys/kernel/ryzen_smu_drv/pm_table_version"

JSON_OUTPUT   = "gnr_telemetry_dump.json"
CSV_OUTPUT    = "gnr_telemetry.csv"

def get_pm_version():
    try:
        with open(VERSION_PATH, "rb") as f:
            return struct.unpack("<I", f.read(4))[0]
    except Exception:
        return 0


def require_supported_hardware():
    """Exit rather than export named fields read from unvalidated offsets.

    This used to print a warning and carry on, which is the worst option: the CSV
    still has a `Package_Power_W` column, it still holds a plausible number, and
    nothing downstream can tell it came from the wrong offset.
    """
    profile, why = get_hardware_profile()
    if profile is None:
        sys.exit(f"refusing to export: {why}\n"
                 f"see gnr_smu/ — the field names would be wrong, not missing.")
    print(f"hardware check: {why}")
    return profile


def get_floats(profile):
    with open(PM_TABLE_PATH, "rb") as f:
        data = f.read(profile.table_size)
    if len(data) != profile.table_size:
        raise ValueError(f"Unexpected table size: {len(data)} bytes")
    return list(struct.unpack(f"<{profile.float_count}f", data))


def csv_output_mode(fieldnames, live_interval):
    """Return ``(mode, write_header)`` without appending to an incompatible CSV."""
    append = (live_interval is not None and os.path.exists(CSV_OUTPUT)
              and os.path.getsize(CSV_OUTPUT) > 0)
    if not append:
        return "w", True

    with open(CSV_OUTPUT, newline="") as f:
        existing_header = next(csv.reader(f), [])
    if existing_header != fieldnames:
        sys.exit(
            f"refusing to append to {CSV_OUTPUT}: its columns do not match the "
            "current hardware profile; move or remove the existing file first"
        )
    return "a", False


def cmd_json():
    profile = require_supported_hardware()
    ver = get_pm_version()
    snapshots = []
    print("Capturing 5 snapshots (10 seconds)...")
    for i in range(5):
        print(f"  Snapshot {i+1}/5...")
        snapshots.append(get_floats(profile))
        if i < 4:
            time.sleep(2)
    export_data = {
        "metadata": {
            "version": hex(ver),
            "table_size": profile.table_size,
            "float_count": profile.float_count,
            "notes": "Generated by GNR-SMU export tool",
            "processor": f"{profile.arch} — {profile.name}",
        },
        "snapshots": snapshots,
    }
    with open(JSON_OUTPUT, "w") as f:
        json.dump(export_data, f, indent=2)
    print(f"\n✅ Exported {len(snapshots)} snapshots -> {JSON_OUTPUT}")


def cmd_csv(live_interval=None):
    profile = require_supported_hardware()
    fields = named_fields(profile)
    fieldnames = [name for name, _, _ in fields]
    mode, write_header = csv_output_mode(fieldnames, live_interval)
    with open(CSV_OUTPUT, mode, newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()

        if live_interval is None:
            d = get_floats(profile)
            writer.writerow(floats_to_row(d, time.time(), profile, fields))
            print(f"✅ Snapshot -> {CSV_OUTPUT}")
        else:
            print(f"Live logging every {live_interval}s -> {CSV_OUTPUT}  (Ctrl+C to stop)")
            n = 0
            try:
                while True:
                    d = get_floats(profile)
                    writer.writerow(floats_to_row(d, time.time(), profile, fields))
                    f.flush()
                    n += 1
                    pidx = live_power_index(profile)
                    pkg = d[pidx] if pidx is not None else float("nan")
                    max_temp = max(profile.lane_values(d, profile.core_temp))
                    print(f"\r  [{n}] Pkg: {pkg:.1f}W  MaxTemp: {max_temp:.1f}°C", end="", flush=True)
                    time.sleep(live_interval)
            except KeyboardInterrupt:
                print(f"\n✅ Stopped after {n} samples.")


def cmd_temps():
    profile = require_supported_hardware()
    d = get_floats(profile)
    print(f"Per-core temperatures — {profile.name}")
    for core in range(profile.cores):
        print(f"Core {core:2}: {profile.lane_values(d, profile.core_temp)[core]:5.1f} °C")


def main():
    parser = argparse.ArgumentParser(description="GNR-SMU Telemetry Exporter")
    parser.add_argument("--csv", action="store_true", help="Export named CSV snapshot")
    parser.add_argument("--live", type=float, metavar="N", help="Live CSV logging every N seconds")
    parser.add_argument("--temps", action="store_true",
                        help="Print one per-core temperature snapshot")
    args = parser.parse_args()

    if args.temps:
        cmd_temps()
    elif args.live is not None:
        cmd_csv(live_interval=args.live)
    elif args.csv:
        cmd_csv()
    else:
        cmd_json()


if __name__ == "__main__":
    main()
