#!/usr/bin/env python3
"""
GNR-SMU Telemetry Exporter — Granite Ridge (Zen 5)
Usage:
  python3 export_telemetry.py              # 5 JSON snapshots -> gnr_telemetry_dump.json
  python3 export_telemetry.py --csv        # named CSV snapshot -> gnr_telemetry.csv
  python3 export_telemetry.py --live N     # CSV live logging every N seconds (Ctrl+C to stop)
"""
import struct
import json
import time
import csv
import sys
import argparse
import os

PM_TABLE_PATH = "/sys/kernel/ryzen_smu_drv/pm_table"
VERSION_PATH  = "/sys/kernel/ryzen_smu_drv/pm_table_version"
JSON_OUTPUT   = "gnr_telemetry_dump.json"
CSV_OUTPUT    = "gnr_telemetry.csv"

# Key named fields: (column_name, float_index, unit)
NAMED_FIELDS = [
    ("timestamp",        None,  "s"),
    ("ppt_limit",        2,     "W"),
    ("edc_limit",        8,     "A"),
    ("tdc_limit",        10,    "A"),
    ("pkg_power",        20,    "W"),
("soc_power", 21, "W"),
("soc_telemetry", 87, "metric"),  # efficiency metric, NOT voltage
("soc_telemetry_metric", 95, "unit"),  # NOT voltage, use d[87] or d[53] instead
    ("vcore_peak",       None,  "V"),   # computed: max(d[309..316])
    ("vcore_avg",        None,  "V"),   # computed: mean(d[309..316])
    ("fclk",             71,    "MHz"),
    ("uclk",             75,    "MHz"),
    ("mclk",             79,    "MHz"),
    ("igpu_power",       107,   "W"),
    ("igpu_clock",       108,   "MHz"),
    ("l3_temp_0",        298,   "C"),
    ("l3_temp_1",        299,   "C"),
    ("pkg_energy",       212,   "J"),
]
# Per-core fields (8 cores)
for _c in range(8):
    NAMED_FIELDS += [
        (f"c{_c}_voltage",    309 + _c, "V"),
        (f"c{_c}_temp",       317 + _c, "C"),
        (f"c{_c}_freq",       325 + _c, "GHz"),
        (f"c{_c}_power",      333 + _c, "W"),
        (f"c{_c}_c0_residency", 357 + _c, "%"),
        (f"c{_c}_c6_residency", 349 + _c, "%"),
        (f"c{_c}_boost_limit",  373 + _c, "GHz"),
    ]


def get_pm_version():
    try:
        with open(VERSION_PATH, "rb") as f:
            return struct.unpack("<I", f.read(4))[0]
    except Exception:
        return 0


def get_floats():
    with open(PM_TABLE_PATH, "rb") as f:
        data = f.read(1828)
    if len(data) != 1828:
        raise ValueError(f"Unexpected table size: {len(data)} bytes")
    return list(struct.unpack("<457f", data))


def floats_to_row(d, ts):
    row = {}
    vcores = [d[309 + i] for i in range(8)]
    for name, idx, _ in NAMED_FIELDS:
        if name == "timestamp":
            row[name] = f"{ts:.3f}"
        elif name == "vcore_peak":
            row[name] = f"{max(vcores):.4f}"
        elif name == "vcore_avg":
            row[name] = f"{sum(vcores)/8:.4f}"
        else:
            row[name] = f"{d[idx]:.4f}"
    return row


def cmd_json():
    ver = get_pm_version()
    print(f"PM Table version: {hex(ver)}")
    if ver != 0x620105:
        print(f"WARNING: unexpected version {hex(ver)}, offsets may be wrong")
    snapshots = []
    print("Capturing 5 snapshots (10 seconds)...")
    for i in range(5):
        print(f"  Snapshot {i+1}/5...")
        snapshots.append(get_floats())
        if i < 4:
            time.sleep(2)
    export_data = {
        "metadata": {
            "version": hex(ver),
            "table_size": 1828,
            "float_count": 457,
            "notes": "Generated by GNR-SMU export tool",
            "processor": "Granite Ridge (Zen 5) — Ryzen 7 9800X3D",
        },
        "snapshots": snapshots,
    }
    with open(JSON_OUTPUT, "w") as f:
        json.dump(export_data, f, indent=2)
    print(f"\n✅ Exported {len(snapshots)} snapshots -> {JSON_OUTPUT}")


def cmd_csv(live_interval=None):
    ver = get_pm_version()
    print(f"PM Table version: {hex(ver)}")
    if ver != 0x620105:
        print(f"WARNING: unexpected version {hex(ver)}, offsets may be wrong")

    fieldnames = [name for name, _, _ in NAMED_FIELDS]
    write_header = not os.path.exists(CSV_OUTPUT) or live_interval is None

    mode = "a" if (live_interval and os.path.exists(CSV_OUTPUT)) else "w"
    with open(CSV_OUTPUT, mode, newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()

        if live_interval is None:
            d = get_floats()
            writer.writerow(floats_to_row(d, time.time()))
            print(f"✅ Snapshot -> {CSV_OUTPUT}")
        else:
            print(f"Live logging every {live_interval}s -> {CSV_OUTPUT}  (Ctrl+C to stop)")
            n = 0
            try:
                while True:
                    d = get_floats()
                    writer.writerow(floats_to_row(d, time.time()))
                    f.flush()
                    n += 1
                    pkg = d[20]
                    max_temp = max(d[317 + i] for i in range(8))
                    print(f"\r  [{n}] Pkg: {pkg:.1f}W  MaxTemp: {max_temp:.1f}°C", end="", flush=True)
                    time.sleep(live_interval)
            except KeyboardInterrupt:
                print(f"\n✅ Stopped after {n} samples.")


def main():
    parser = argparse.ArgumentParser(description="GNR-SMU Telemetry Exporter")
    parser.add_argument("--csv", action="store_true", help="Export named CSV snapshot")
    parser.add_argument("--live", type=float, metavar="N", help="Live CSV logging every N seconds")
    args = parser.parse_args()

    if args.live is not None:
        cmd_csv(live_interval=args.live)
    elif args.csv:
        cmd_csv()
    else:
        cmd_json()


if __name__ == "__main__":
    main()
