#!/usr/bin/env python3
import struct
import json
import time

PM_TABLE_PATH = "/sys/kernel/ryzen_smu_drv/pm_table"
VERSION_PATH = "/sys/kernel/ryzen_smu_drv/pm_table_version"
OUTPUT_FILE = "gnr_telemetry_dump.json"

def get_pm_version():
    try:
        with open(VERSION_PATH, "rb") as f:
            return hex(struct.unpack("<I", f.read(4))[0])
    except:
        return "UNKNOWN"

def get_floats():
    with open(PM_TABLE_PATH, "rb") as f:
        data = f.read(1828)
    return list(struct.unpack(f"<{len(data)//4}f", data))

def main():
    print("--- GNR-SMU Telemetry Exporter ---")
    ver = get_pm_version()
    print(f"Detected PM Table Version: {ver}")
    
    # We take 5 snapshots spaced by 2 seconds to capture idle vs active moments automatically if the user is doing things
    snapshots = []
    print("Capturing 5 snapshots (wait 10 seconds)...")
    for i in range(5):
        print(f"Snapshot {i+1}/5...")
        snapshots.append(get_floats())
        time.sleep(2)
        
    export_data = {
        "metadata": {
            "version": ver,
            "table_size": 1828,
            "float_count": len(snapshots[0]),
            "notes": "Generated by GNR-SMU export tool",
            "processor": "Granite Ridge (Zen 5)"
        },
        "snapshots": snapshots
    }
    
    with open(OUTPUT_FILE, "w") as f:
        json.dump(export_data, f, indent=2)
        
    print(f"\\n✅ Successfully exported {len(snapshots)} snapshots to {OUTPUT_FILE}!")
    print("You can share this JSON file with the community to crowdsource 'Unk' floats!")

if __name__ == "__main__":
    main()
